name: CI
on:
  push:
    paths-ignore:
    - '**.md'
    - '**.png'
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
    - env:
        DOCKER_APP_IMAGE_NAME: "docker.pkg.github.com/hasadna/open-bus-stride-db/open-bus-stride-db"
        DOCKER_BACKUP_IMAGE_NAME: "docker.pkg.github.com/hasadna/open-bus-stride-db/open-bus-stride-db-backup"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HASADNA_K8S_DEPLOY_KEY: ${{ secrets.HASADNA_K8S_DEPLOY_KEY }}
        SIRI_ETL_DEPLOY_KEY: ${{ secrets.SIRI_ETL_DEPLOY_KEY }}
        STRIDE_API_DEPLOY_KEY: ${{ secrets.STRIDE_API_DEPLOY_KEY }}
        STRIDE_ETL_DEPLOY_KEY: ${{ secrets.STRIDE_ETL_DEPLOY_KEY }}
      run: |
        curl -s https://raw.githubusercontent.com/OriHoch/uumpa-ci-toolbox/65a0704332e63d51f63981dbb25cd83682dc4078/bin/github_actions_install.sh \
          | bash -s 65a0704332e63d51f63981dbb25cd83682dc4078 OriHoch/uumpa-ci-toolbox &&\
        uci github actions self-checkout --config-user-name "open-bus-stride-db-ci" &&\
        uci github actions docker-login &&\
        uci docker build-cache \
          --cache-from "${DOCKER_APP_IMAGE_NAME}:latest" \
          -- -t app . &&\
        uci docker tag-push \
          --source-tag-name app \
          --push-tag-name "${DOCKER_APP_IMAGE_NAME}:${GITHUB_SHA}" &&\
        uci docker build-cache \
          --cache-from "${DOCKER_BACKUP_IMAGE_NAME}:latest" \
          -- -t backup backup &&\
        uci docker tag-push \
          --source-tag-name backup \
          --push-tag-name "${DOCKER_BACKUP_IMAGE_NAME}:${GITHUB_SHA}" &&\
        docker run -e POSTGRES_PASSWORD=123456 -p 5432:5432 -v `pwd`/.data/db:/var/lib/postgresql/data -d postgres:13 &&\
        sleep 5 &&\
        docker run --network host -e SQLALCHEMY_URL=postgresql://postgres:123456@localhost app &&\
        docker build -t docgen -f docgen.Dockerfile . &&\
        docker run --network host -e SQLALCHEMY_URL=postgresql://postgres:123456@localhost \
          -v "`pwd`/docgen_output:/output" \
          --entrypoint python docgen bin/docgen.py /output &&\
        if ! diff docgen_output/DATA_MODEL.md ./DATA_MODEL.md || ! diff docgen_output/dbschema.png ./dbschema.png; then
          cp -f docgen_output/DATA_MODEL.md ./DATA_MODEL.md &&\
          cp -f docgen_output/dbschema.png ./dbschema.png &&\
          git add ./DATA_MODEL.md && git add ./dbschema.png &&\
          git commit -m "automatic update of the data model documentation" &&\
          git push
        fi &&\
        if [ "$(uci github actions get-branch-name)" == "main" ]; then
          uci docker tag-push \
            --source-tag-name app \
            --push-tag-name "${DOCKER_APP_IMAGE_NAME}:latest" &&\
          uci docker tag-push \
            --source-tag-name backup \
            --push-tag-name "${DOCKER_BACKUP_IMAGE_NAME}:latest" &&\
          if ! uci git check-last-commit-message --contains --no-deploy; then
            cd `mktemp -d` &&\
            uci git checkout \
              --github-repo-name hasadna/hasadna-k8s \
              --branch-name master \
              --ssh-key "${HASADNA_K8S_DEPLOY_KEY}" \
              --path hasadna-k8s \
              --config-user-name open-bus-stride-db-ci &&\
            cd hasadna-k8s &&\
            python update_yaml.py '{"strideDbAppImage":"'"${DOCKER_APP_IMAGE_NAME}:${GITHUB_SHA}"'"}' apps/openbus/values-hasadna-auto-updated.yaml &&\
            git add apps/openbus/values-hasadna-auto-updated.yaml && git commit -m "automatic update of open bus stride db" &&\
            git push origin master &&\
            cd `mktemp -d` &&\
            uci git checkout \
              --github-repo-name hasadna/open-bus-siri-etl \
              --branch-name main \
              --ssh-key "${SIRI_ETL_DEPLOY_KEY}" \
              --path open-bus-siri-etl \
              --config-user-name open-bus-stride-db-ci &&\
            cd open-bus-siri-etl &&\
            bin/update_stride_db_dependencies.py "${GITHUB_SHA}" &&\
            git commit -m "automatic update of open bus stride db dependencies" &&\
            git push origin main &&\
            cd `mktemp -d` &&\
            uci git checkout \
              --github-repo-name hasadna/open-bus-stride-api \
              --branch-name main \
              --ssh-key "${STRIDE_API_DEPLOY_KEY}" \
              --path open-bus-stride-api \
              --config-user-name open-bus-stride-db-ci &&\
            cd open-bus-stride-api &&\
            bin/update_stride_db_dependencies.py "${GITHUB_SHA}" &&\
            git commit -m "automatic update of open bus stride db dependencies" &&\
            git push origin main &&\
            cd `mktemp -d` &&\
            uci git checkout \
              --github-repo-name hasadna/open-bus-stride-etl \
              --branch-name main \
              --ssh-key "${STRIDE_ETL_DEPLOY_KEY}" \
              --path open-bus-stride-etl \
              --config-user-name open-bus-stride-db-ci &&\
            cd open-bus-stride-etl &&\
            echo "${GITHUB_SHA}" > stride-db-latest-commit.txt &&\
            git add stride-db-latest-commit.txt &&\
            git commit -m "automatic update of open bus stride db dependencies" &&\
            git push origin main
          fi
        fi
